# Generated by Django 3.0 on 2020-07-05 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Astro_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', multiselectfield.db.fields.MultiSelectField(choices=[('Electional astrology', 'Electional astrology'), ('Horary astrology', 'Horary astrology'), ('Horoscopic astrology', 'Horoscopic astrology'), ('Indian astrology', 'Indian astrology'), ('Tibetan astrology', 'Tibetan astrology'), ('Western astrology', 'Western astrology'), ('Tropical astrology', 'Tropical astrology'), ('Agricultural astrology', 'Agricultural astrology'), ('Numerology', 'Numerology'), ('Tarot divination', 'Tarot divination'), ('Financial astrology', 'Financial astrology'), ('Locational astrology', 'Locational astrology'), ('Psychological astrology', 'Psychological astrology'), ('Sun sign astrology', 'Sun sign astrology')], max_length=265)),
                ('language', multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Gujarati', 'Guarati'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil')], max_length=36)),
                ('experience', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=200)),
                ('astroprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Astro_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(null=True, upload_to='images/')),
                ('user_role', models.CharField(choices=[('Customer', 'Customer'), ('Astrologer', 'Astrologer')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='astro_profile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
