# Generated by Django 3.0 on 2020-07-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200706_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
