# Generated by Django 3.0 on 2020-07-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200706_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.CharField(default='good', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='imansyah-muhamad-putera-KchIV_GDy6U-unsplash.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Astrologer', 'Astrologer')], max_length=30),
        ),
    ]
